/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/navigation`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/movies`; params?: Router.UnknownInputParams; } | { pathname: `/tv-shows`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/movies` | `/movies`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tv-shows` | `/tv-shows`; params?: Router.UnknownInputParams; } | { pathname: `/services/api`; params?: Router.UnknownInputParams; } | { pathname: `/components/VideoCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/Header`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modal)'}/player` | `/player`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modal)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modal)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `/context/AuthContext`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/navigation`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/movies`; params?: Router.UnknownOutputParams; } | { pathname: `/tv-shows`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/movies` | `/movies`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tv-shows` | `/tv-shows`; params?: Router.UnknownOutputParams; } | { pathname: `/services/api`; params?: Router.UnknownOutputParams; } | { pathname: `/components/VideoCard`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Header`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modal)'}/player` | `/player`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modal)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modal)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/context/AuthContext`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/navigation${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/movies${`?${string}` | `#${string}` | ''}` | `/tv-shows${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/movies${`?${string}` | `#${string}` | ''}` | `/movies${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tv-shows${`?${string}` | `#${string}` | ''}` | `/tv-shows${`?${string}` | `#${string}` | ''}` | `/services/api${`?${string}` | `#${string}` | ''}` | `/components/VideoCard${`?${string}` | `#${string}` | ''}` | `/components/Header${`?${string}` | `#${string}` | ''}` | `${'/(modal)'}/player${`?${string}` | `#${string}` | ''}` | `/player${`?${string}` | `#${string}` | ''}` | `${'/(modal)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `${'/(modal)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/context/AuthContext${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/navigation`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/movies`; params?: Router.UnknownInputParams; } | { pathname: `/tv-shows`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/movies` | `/movies`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tv-shows` | `/tv-shows`; params?: Router.UnknownInputParams; } | { pathname: `/services/api`; params?: Router.UnknownInputParams; } | { pathname: `/components/VideoCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/Header`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modal)'}/player` | `/player`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modal)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modal)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `/context/AuthContext`; params?: Router.UnknownInputParams; };
    }
  }
}
